# Generated by Django 4.2.6 on 2024-01-18 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_event', models.CharField(max_length=60, verbose_name='Эвент')),
                ('info_event', models.CharField(max_length=1500, verbose_name='Информация')),
                ('start_time', models.DateTimeField(verbose_name='Время начала')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('publish', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='Ссылка')),
                ('chanel', models.CharField(verbose_name='id_евента_в_канале')),
            ],
            options={
                'verbose_name': 'Эвент',
                'verbose_name_plural': 'Эвенты',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(unique=True, verbose_name='ID пользователя')),
                ('name', models.TextField(verbose_name='Имя пользователя')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('choice_month', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='EventIsRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_blog.event')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_blog.profile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='user_create',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_blog.profile'),
        ),
    ]
