# Generated by Django 4.2.6 on 2024-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.CharField(blank=True, max_length=800, verbose_name='Ссылка'),
        ),
    ]
