# Generated by Django 5.0 on 2023-12-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_blog', '0016_alter_event_info_event_alter_event_start_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
